import pygame

TILE_OCEAN = 0
TILE_EMPTY = 1
TILE_CLOUDY = 5
TILE_SIZE = 50

grid = [[TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_OCEAN, TILE_EMPTY, TILE_OCEAN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, 
TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_OCEAN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_OCEAN, TILE_OCEAN, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_OCEAN, TILE_OCEAN, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, 
TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_OCEAN, TILE_OCEAN, 
TILE_OCEAN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_OCEAN, TILE_OCEAN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_OCEAN, TILE_OCEAN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_OCEAN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_OCEAN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, 
TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_OCEAN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_OCEAN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_OCEAN, TILE_OCEAN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_OCEAN, TILE_OCEAN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, 
TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, 
TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_OCEAN, TILE_OCEAN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_OCEAN, TILE_OCEAN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_OCEAN, TILE_OCEAN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_OCEAN, TILE_OCEAN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN], [TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, 
TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_EMPTY, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN,TILE_OCEAN,TILE_OCEAN,TILE_OCEAN,TILE_OCEAN,TILE_OCEAN], [TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN,TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN, TILE_OCEAN]]

print(len(grid))
print(len(grid[0]))
# Define regions
regions = [
    (slice(0, 12), slice(0, 10),True),
    (slice(12, 24), slice(0, 10),False),
    (slice(24, 36), slice(0, 10),True),
    (slice(36, 46), slice(0, 10),True),
    (slice(0, 12), slice(10, 20),True),
    (slice(12, 24), slice(10, 20),True),
    (slice(24, 36), slice(10, 20),True),
    (slice(36, 46), slice(10, 20),True),
    (slice(0, 12), slice(20, 30),True),
    (slice(12, 24), slice(20, 30),True),
    (slice(24, 36), slice(20, 30),True),
    (slice(36, 46), slice(20, 30),True)
]
# Ensure regions are within bounds of the grid
def is_within_bounds(grid, region):
    max_rows = len(grid)
    max_cols = len(grid[0]) if max_rows > 0 else 0
    return region[0].stop <= max_rows and region[1].stop <= max_cols

# Initialize the grid with all regions covered by TILE_CLOUDY except the first one
def initialize_grid(grid, regions):
    for i, region in enumerate(regions):
        if i != 1:  # Skip the first region to keep it uncovered
            for row in range(region[0].start, region[0].stop):
                for col in range(region[1].start, region[1].stop):
                    if grid[row][col] == TILE_EMPTY:
                        grid[row][col] = TILE_CLOUDY

initialize_grid(grid, regions)



# Example of unlocking the second region
#unlock_region(grid, regions[2])

# Print the grid to visualize the changes
for row in grid:
    print(row)

tile_images = {
 

    1: pygame.transform.scale(pygame.image.load('Data/windmill.png'), (50,50)),
    2: pygame.transform.scale(pygame.image.load('Data/research1full.png'), (50,50)),
    3: pygame.transform.scale(pygame.image.load('Data/battery.png'), (50,50)),
    4: pygame.transform.scale(pygame.image.load('Data/officefull.png'), (50,50)),
    5: pygame.transform.scale(pygame.image.load('Data/solarpanelfull.png'), (50,50)),
    6: pygame.transform.scale(pygame.image.load('Data/generatorfull.png'), (50,50)),
    7: pygame.transform.scale(pygame.image.load('Data/coalfactory.png'), (50,50)),
    8: pygame.transform.scale(pygame.image.load('Data/office2.png'), (50,50)),
    9: pygame.transform.scale(pygame.image.load('Data/gasburnerfull.png'), (50,50)),
    10: pygame.transform.scale(pygame.image.load('Data/generator2full.png'), (50,50)),
    11: pygame.transform.scale(pygame.image.load('Data/research2full.png'), (50,50)),
    12: pygame.transform.scale(pygame.image.load('Data/nuclearreactorfull.png'), (50,50)),
    13: pygame.transform.scale(pygame.image.load('Data/office3.png'), (50,50)),
    14: pygame.transform.scale(pygame.image.load('Data/thermoreactorfull.png'), (50,50)),
    15: pygame.transform.scale(pygame.image.load('Data/office4.png'), (50,50)),
    16: pygame.transform.scale(pygame.image.load('Data/fusion.png'), (50,50)),
    17: pygame.transform.scale(pygame.image.load('Data/generator3full.png'), (50,50)),
    18: pygame.transform.scale(pygame.image.load('Data/office5.png'), (50,50)),
    19: pygame.transform.scale(pygame.image.load('Data/tokamak.png'), (50,50)),
    20: pygame.transform.scale(pygame.image.load('Data/stellarator.png'), (50,50)),
    21: pygame.transform.scale(pygame.image.load('Data/generator4.png'), (50,50)),
    22: pygame.transform.scale(pygame.image.load('Data/office6.png'), (50,50)),
    23: pygame.transform.scale(pygame.image.load('Data/ufo.png'), (50,50)),
    24: pygame.transform.scale(pygame.image.load('Data/arc.png'), (50,50)),
    25: pygame.transform.scale(pygame.image.load('Data/office7.png'), (50,50)),
    26: pygame.transform.scale(pygame.image.load('Data/research3full.png'), (50,50)),
    27: pygame.transform.scale(pygame.image.load('Data/cosmic.png'), (50,50)),
    28: pygame.transform.scale(pygame.image.load('Data/geothermal.png'), (50,50)),
    29: pygame.transform.scale(pygame.image.load('Data/generator5full2.png'), (50,50)),
    30: pygame.transform.scale(pygame.image.load('Data/tesla.png'), (50,50)),
    31: pygame.transform.scale(pygame.image.load('Data/office8.png'), (50,50)),
    32: pygame.transform.scale(pygame.image.load('Data/dark.png'), (50,50))
}

converter_menu_images = {
    1: pygame.transform.scale(pygame.image.load('Data/generator1.png'), (40, 40)),
    2: pygame.transform.scale(pygame.image.load('Data/generator2fullmenu.png'), (40, 40)),
    3: pygame.transform.scale(pygame.image.load('Data/generator1.png'), (40, 40)),
    4: pygame.transform.scale(pygame.image.load('Data/generator2fullmenu.png'), (40, 40)),
    5: pygame.transform.scale(pygame.image.load('Data/generator3fullmenu.png'), (40, 40))

    
}
generator_menu_images = {
 
    1 : pygame.transform.scale(pygame.image.load('Data/windmill_menu.png'), (40, 40)),
    2 : pygame.transform.scale(pygame.image.load('Data/convertermenu.png'), (40, 40)),
    3 : pygame.transform.scale(pygame.image.load('Data/coalfactorymenu.png'), (40, 40)),
    4: pygame.transform.scale(pygame.image.load('Data/gasburnerfull.png'), (40, 40)),
    5: pygame.transform.scale(pygame.image.load('Data/nuclearreactorfull.png'), (40, 40)),
    6: pygame.transform.scale(pygame.image.load('Data/generator4full.png'), (40, 40)),
    7: pygame.transform.scale(pygame.image.load('Data/generator5full.png'), (40, 40)),
    8 : pygame.transform.scale(pygame.image.load('Data/convertermenu.png'), (40, 40)),
    9 : pygame.transform.scale(pygame.image.load('Data/coalfactorymenu.png'), (40, 40)),
    10: pygame.transform.scale(pygame.image.load('Data/gasburnerfull.png'), (40, 40)),
    11: pygame.transform.scale(pygame.image.load('Data/nuclearreactorfull.png'), (40, 40)),
    12: pygame.transform.scale(pygame.image.load('Data/generator4full.png'), (40, 40)),
    13: pygame.transform.scale(pygame.image.load('Data/generator5full.png'), (40, 40)),
    14: pygame.transform.scale(pygame.image.load('Data/generator6full.png'), (40, 40)),
    15: pygame.transform.scale(pygame.image.load('Data/generator5full.png'), (40, 40))
 
}
office_menu_images = {
 
    1 : pygame.transform.scale(pygame.image.load('Data/office.png'), (40, 40)),
    2 : pygame.transform.scale(pygame.image.load('Data/office2menu.png'), (40, 40)),
    3 : pygame.transform.scale(pygame.image.load('Data/office3menu.png'), (40, 40)),
    4 : pygame.transform.scale(pygame.image.load('Data/office.png'), (40, 40)),
    5 : pygame.transform.scale(pygame.image.load('Data/office2menu.png'), (40, 40)),
    6 : pygame.transform.scale(pygame.image.load('Data/office3menu.png'), (40, 40)),   
    7 : pygame.transform.scale(pygame.image.load('Data/office2menu.png'), (40, 40)),
    8 : pygame.transform.scale(pygame.image.load('Data/office3menu.png'), (40, 40))
}
researchlab_menu_images = {
 
    1 : pygame.transform.scale(pygame.image.load('Data/research1.png'), (40, 40)),
    2 : pygame.transform.scale(pygame.image.load('Data/research2.png'), (40, 40)),
    3 : pygame.transform.scale(pygame.image.load('Data/research3.png'), (40, 40))
}

explosion_images = {
    1 : pygame.transform.scale(pygame.image.load('Data/explosion1.png'), (50,50)),
    2 : pygame.transform.scale(pygame.image.load('Data/explosion2.png'), (50,50)),
    3 : pygame.transform.scale(pygame.image.load('Data/explosion3.png'), (50,50)),
    4 : pygame.transform.scale(pygame.image.load('Data/explosion4.png'), (50,50)),
    5 : pygame.transform.scale(pygame.image.load('Data/explosion5_scuffed.png'), (50,50)),
    6 : pygame.transform.scale(pygame.image.load('Data/explosion6.png'), (50,50)),
    7 : pygame.transform.scale(pygame.image.load('Data/explosion7.png'), (50,50))
}

battery_images = {
    1:pygame.transform.scale(pygame.image.load('Data/batterymenu.png'), (40,40)),
    2:pygame.transform.scale(pygame.image.load('Data/battery.png'), (50,50))

}

